### ISSUE TITLE
Camillilinks: 2 responses for posting a recent link in a thread when "also send to channel" is checked.

### ISSUE THREAD

**Issue by allenhumphreys** [bugKrusha/Camille#22]
Ignoring the second message should be easy via checking the message type for [`thread_broadcast`](https://api.slack.com/events/message/thread_broadcast). The blocker on this is that message type is not currently supported by Chameleon.

**Comment by allenhumphreys** [comment]
I am working on this issue, can't assign myself though :-)

**Comment by bugKrusha** [comment]
😔 so I tried assigning it to you but it doesn't seem that I can assign issues to people who aren't _collaborators_. Do you know if that is the case?
