### ISSUE TITLE
Allowlist URLs

### ISSUE THREAD

**Issue by mergesort** [bugKrusha/Camille#24]
This isn't a definitive list, but the current list of links I've come across which are unnecessary in Slack.

`developer.apple.com/*`
`*.slack.com`
`github.com/*`
`youtube.com/*`

**Comment by Naxum** [comment]
We probably also want to skip general knowledge databases, or things that aren't timely.

- Wikipedia articles (regardless of language, mobile subdomains)
- Maybe NSHipster, etc?

**Comment by ZevEisenberg** [comment]
Whitelist → allowlist? Although I'm partial to nicelist and naughtylist, myself 😉
