### ISSUE TITLE
Camille Responds To Links In Deleted Messages

### ISSUE THREAD

**Issue by mergesort** [bugKrusha/Camille#25]
If you post a link and then delete the message, the link remains cached and so Camille will respond by directing you to a deleted message.

Test case:
Post a link.
Delete the message.
Re-post the link.
See Camille respond.

**Comment by IanKeen** [comment]
Should be resolved by: https://github.com/bugKrusha/Camille/blob/master/Tests/SlackBotKitTests/CamillinkTests.swift#L46-L48
