### ISSUE TITLE
Camille double-counts ++ commands if a link gets unfurled

### ISSUE THREAD

**Issue by davedelong** [bugKrusha/Camille#37]
I just did "@someuser++ https://example.com".

Camille got the initial karma+1 from me posting the message, but then did another one when `example.com` was unfurled and the preview shown.

**Comment by IanKeen** [comment]
This should be resolved now!
https://github.com/bugKrusha/Camille/blob/master/Tests/SlackBotKitTests/KarmaTests.swift#L69
