### ISSUE TITLE
Responds with incorrect number on “top users” request

### ISSUE THREAD

**Issue by huntermonk** [bugKrusha/Camille#4]
When Jazbo requested top 10, Camille responded with:

> We only have 10
> 1) *@bugkrusha* :  1
> 2) *@iankeen* :  1

![65c46560-bac6-4929-be49-c272d89c29b5](https://user-images.githubusercontent.com/9557484/48155285-867f1700-e27f-11e8-9e46-afcae1911067.jpeg)

It’s also possible she was triggered by Soroush’s request for top users - it’s unclear.

**Comment by mergesort** [comment]
Closing as this works now. 😄
